//ecd:1144772079H20250415013947_V1.0
package io.elasticore.blueprint.domain.bbs.port;

import java.util.*;
import io.elasticore.blueprint.domain.bbs.entity.*;
import io.elasticore.blueprint.domain.bbs.dto.*;


import org.springframework.data.domain.Page;
import io.elasticore.runtime.port.*;


/**
 * Defines a Port Adapter interface for transforming between DTOs and entities.
 *
 * The implementation of this interface is dynamically generated by ElastiCORE
 * at runtime based on the underlying domain model.
 *
 * Modify this code only as specified in the ElastiCORE guidelines
 * to avoid regeneration conflicts.
 *
 * Generated and managed by ElastiCORE.
 */
@DbmsService(id="bbs.CandleDbPort" ,datasource="main" ,sqlSource="blueprint/bbs/model/dbms.yml")
public interface CandleDbPort   {

    /*
     * 특정 마켓에서 최고가와 시간 조회
    */
    MaxPriceResult findMaxPriceByMarket(MaxPriceRequest input);
    

}
