//ecd:764944526H20250521182055_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.proto;


import io.grpc.stub.StreamObserver;
import io.elasticore.springboot3.mapper.Mapper;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;



@AllArgsConstructor
@Component
public class CarInfoPortServiceProvider extends CarInfoPortServiceGrpc.CarInfoPortServiceImplBase {


    /*
     * 브랜드별 차량 정보 조회
    */
    public void  findByBrand(CarInfo2Input request, StreamObserver<CarInfo2Output> responseObserver) {
      // TODO: implements
      CarInfo2Output.Builder builder = CarInfo2Output.newBuilder();
      //Mapper.of(output, builder).execute();
      CarInfo2Output response = builder.build();
      responseObserver.onNext(response);
      responseObserver.onCompleted();
    }
}
