//ecd:-1936024586H20250522154355_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.proto;


import io.grpc.stub.StreamObserver;
import io.elasticore.springboot3.mapper.Mapper;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;



/**
 * gRPC Provider class for handling CarInfoPortService service logic.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * generating proto-based Spring Boot service scaffolding using DSL.
 *
 * This file is generated once and is not managed by ElastiCORE after creation.
 * You may freely modify the content as needed.
 *
 * To regenerate this class via ElastiCORE, delete the entire file before re-running the build.
 * ElastiCORE will then treat the class as missing and recreate it accordingly.
 */
@AllArgsConstructor
@Component
public class CarInfoPortServiceProvider extends CarInfoPortServiceGrpc.CarInfoPortServiceImplBase {


    /*
     * 브랜드별 차량 정보 조회
    */
    public void  findByBrand(CarInfo2Input request, StreamObserver<CarInfo2Output> responseObserver) {
        // TODO: implement for gRPC service
        CarInfo2Output.Builder builder = CarInfo2Output.newBuilder();
        //Mapper.of(output, builder).execute();
        CarInfo2Output response = builder.build();
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
