

entity:
  BaseModel:
    meta: template
    fields:
      insertId: string @notnull @len(20) @label('등록자 Id')
      insertDtm: datetime @notnull @label('등록일시')
      modifyId: string @notnull @len(20) @label('수정자 Id')
      modifyDtm: datetime @notnull @label('수정일시')

