//ecd:-1480663489H20250411151034_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.service;

import io.elasticore.blueprint.domain.parts.repository.*;
import org.springframework.stereotype.Service;

/**
 *
 * This class is intended for custom business logic that extends or overrides the default behavior
 * provided by CarInfoCoreService.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */

@Service
public class CarInfoService extends CarInfoCoreService {

    public CarInfoService(PartsRepositoryHelper helper) {
        super(helper);
    }

}
