//ecd:796904007H20250411111444_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.service;

import io.elasticore.blueprint.domain.parts.entity.CarModel;
import io.elasticore.blueprint.domain.parts.entity.Q;
import io.elasticore.blueprint.domain.parts.repository.*;
import io.elasticore.springboot3.entity.Op;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * This class is intended for custom business logic that extends or overrides the default behavior
 * provided by CarModelCoreService.
 * <p>
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 * <p>
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */

@Service
public class CarModelService extends CarModelCoreService {

    public CarModelService(PartsRepositoryHelper helper) {
        super(helper);
    }


    public List<CarModel> getCarModelList(String catalogId) {

        Specification<CarModel> sp = Q.CarModel.catalog().catalogId(Op.EQ, catalogId);

        List<CarModel> result = helper.getCarModel().findAll(sp);
        return result;
    }


    public PartsRepositoryHelper getHelper() {
        return helper;
    }
}
