//ecd:1911589549H20250425111000_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.service;

import io.elasticore.blueprint.domain.parts.repository.*;
import org.springframework.stereotype.Service;

/**
 *
 * This class is intended for custom business logic that extends or overrides the default behavior
 * provided by ParamInfoCoreService.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */

@Service
public class ParamInfoService extends ParamInfoCoreService {

    public ParamInfoService(PartsRepositoryHelper helper) {
        super(helper);
    }

}
