//ecd:-665650614H20250425111000_V1.0
package io.elasticore.blueprint.domain.parts.port;

import java.util.*;
import io.elasticore.blueprint.domain.parts.entity.*;
import io.elasticore.blueprint.domain.parts.dto.*;


import org.springframework.data.domain.Page;
import io.elasticore.runtime.port.*;


/**
 * Defines a Port Adapter interface for transforming between DTOs and entities.
 *
 * The implementation of this interface is dynamically generated by ElastiCORE
 * at runtime based on the underlying domain model.
 *
 * Modify this code only as specified in the ElastiCORE guidelines
 * to avoid regeneration conflicts.
 *
 * Generated and managed by ElastiCORE.
 */
@DbmsService(id="parts.CarInfoPortService" ,datasource="main" ,sqlSource="blueprint/parts/port/dbms.yml")
public interface CarInfoPortService   {

    /*
     * 브랜드별 차량 정보 조회
    */
    List<CarInfoOutput> findByBrand(CarInfoInput input);
    

}
