//ecd:-1304802378H20250425111000_V1.0
package io.elasticore.blueprint.domain.parts.port;

import java.util.*;
import io.elasticore.blueprint.domain.parts.entity.*;
import io.elasticore.blueprint.domain.parts.dto.*;


import org.springframework.data.domain.Page;
import io.elasticore.runtime.port.*;


/**
 * Defines a Port Adapter interface for transforming between DTOs and entities.
 *
 * The implementation of this interface is dynamically generated by ElastiCORE
 * at runtime based on the underlying domain model.
 *
 * Modify this code only as specified in the ElastiCORE guidelines
 * to avoid regeneration conflicts.
 *
 * Generated and managed by ElastiCORE.
 */
@ExternalService(protocol="http", id="parts.EchoService" ,url="https://echo.free.beeceptor.com")
public interface EchoService   {

    /*
     * testEcho
    */
    @HttpEndpoint(url="/gateway/chn-sfa/api/plan/list", method="POST", contentType="application/json", paramNames="body")
    java.util.HashMap testEcho(MsgInput2 body);
    

}
