//ecd:-1322794080H20250416121357_V1.0
package io.elasticore.blueprint.domain.parts.port;

import java.util.*;
import io.elasticore.blueprint.domain.parts.entity.*;
import io.elasticore.blueprint.domain.parts.dto.*;


import org.springframework.data.domain.Page;
import io.elasticore.runtime.port.*;


/**
 * Defines a Port Adapter interface for transforming between DTOs and entities.
 *
 * The implementation of this interface is dynamically generated by ElastiCORE
 * at runtime based on the underlying domain model.
 *
 * Modify this code only as specified in the ElastiCORE guidelines
 * to avoid regeneration conflicts.
 *
 * Generated and managed by ElastiCORE.
 */
@ExternalService(protocol="http", id="parts.PartsCatalogAdapter" ,url="https://api.parts-catalogs.com", authKey="OEM-API-B8DC10AC-88BA-430B-9800-2A6D1DB6F95C")
public interface PartsCatalogAdapter   {

    /*
     * 차량 카탈로그(브랜드) 목록 정보
    */
    @HttpEndpoint(url="/v1/catalogs/", method="GET", contentType="application/json", paramNames="")
    java.util.List getCatalogs();
    
    /*
     * 브랜드별 차량 모델 목록 정보
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/models", method="GET", contentType="application/json", paramNames="catalogId")
    java.util.List<PartInfo> getCarModelList(String catalogId);
    
    /*
     * 모델별 차량 목록 정보
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/cars2", method="GET", contentType="application/json", paramNames="catalogId,modelId,page")
    java.util.List getCarInfoList(String catalogId,String modelId,Integer page);
    
    /*
     * 차량 상세 정보
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/cars2/{carId}", method="GET", contentType="application/json", paramNames="catalogId,carId")
    java.util.Map getCarInfo(String catalogId,String carId);
    
    /*
     * 차량 파라미터 정보
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/cars-parameters", method="GET", contentType="application/json", paramNames="catalogId,modelIf")
    java.util.Map getCarParams(String catalogId,String modelIf);
    
    /*
     * 대차 번호별 정보
    */
    @HttpEndpoint(url="/v1/car/info", method="GET", contentType="application/json", paramNames="q")
    java.util.List getCarInfoByVIN(String q);
    
    /*
     * getCatalogGroupList
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/groups2", method="GET", contentType="application/json", paramNames="catalogId")
    java.util.List getCatalogGroupList(String catalogId);
    
    /*
     * getCatalogGroupSuggestList
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/groups-suggest", method="GET", contentType="application/json", paramNames="catalogId")
    java.util.List getCatalogGroupSuggestList(String catalogId);
    
    /*
     * getParts
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/parts", method="GET", contentType="application/json", paramNames="catalogId")
    java.util.List getParts(String catalogId);
    
    /*
     * getGroupstree
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/groups-tree", method="GET", contentType="application/json", paramNames="catalogId")
    java.util.List getGroupstree(String catalogId);
    
    /*
     * getSchemas
    */
    @HttpEndpoint(url="/v1/catalogs/{catalogId}/schemas", method="GET", contentType="application/json", paramNames="catalogId")
    java.util.Map getSchemas(String catalogId);
    

}
