//ecd:2101253828H20250520141405_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.bbs.service;

import io.elasticore.blueprint.domain.bbs.repository.*;
import org.springframework.stereotype.Service;

/**
 *
 * This class is intended for custom business logic that extends or overrides the default behavior
 * provided by ArticlePartCoreService.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */

@Service
public class ArticlePartService extends ArticlePartCoreService {

    public ArticlePartService(BbsRepositoryHelper helper) {
        super(helper);
    }

}
