//ecd:-1680171732H20250425111000_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.*;
import io.elasticore.blueprint.domain.parts.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing CarPart entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/carPart")
@RequiredArgsConstructor
@Tag(name = "CarPart (카탈로그 그룹 정보)", description = "API for managing 카탈로그 그룹 정보 entities.")
public class CarPartController {

    private final CarPartService carPartService;


    @Operation(summary = "Create a new CarPart", description = "Registers a new CarPart in the system.")
    @PostMapping
    public CarPartDTO create(@Valid @RequestBody CarPartDTO inputDto) {
        return carPartService.save(inputDto);
    }


    @Operation(summary = "Retrieve a CarPart by ID", description = "Fetches a single CarPart using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CarPart found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = CarPartDTO.class))}),
            @ApiResponse(responseCode = "404", description = "CarPart not found", content = @Content)
    })
    @GetMapping("/{id}")
    public ResponseEntity<CarPartDTO> findById(@PathVariable("id") String id) {
        Optional<CarPartDTO> findOptional = carPartService.findById(id);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search CarPart data", description = "Searches for CarPart records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<CarPartDTO> search(@RequestBody CarPartSrchDTO searchDTO) {
        return carPartService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing CarPart", description = "Updates the details of an existing CarPart by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CarPart updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = CarPartDTO.class))}),
            @ApiResponse(responseCode = "404", description = "CarPart not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<CarPartDTO> update(@RequestBody CarPartDTO updateDto) {
        CarPartDTO resultDto = carPartService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple CarPart entities", description = "Deletes a list of CarPart entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each CarPart entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more CarPart entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<CarPartKeyDTO> delDtoList) {
        List<Boolean> result = carPartService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a CarPart", description = "Deletes a CarPart from the system using its unique identifier.")
    @DeleteMapping("/{id}")
    public ResponseEntity<Boolean> delete(@PathVariable("id") String id) {
        if (!carPartService.findById(id).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = carPartService.deleteById(id);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for CarPartDTO",
        description = "Fetches metadata for the CarPartDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(CarPartDTO.class));
    }
}
