//ecd:-1234260704H20250425111000_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.*;
import io.elasticore.blueprint.domain.parts.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing CarProfile entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/carProfile")
@RequiredArgsConstructor
@Tag(name = "CarProfile (차량정보)", description = "API for managing 차량정보 entities.")
public class CarProfileController {

    private final CarProfileService carProfileService;


    @Operation(summary = "Create a new CarProfile", description = "Registers a new CarProfile in the system.")
    @PostMapping
    public CarProfileDTO create(@Valid @RequestBody CarProfileDTO inputDto) {
        return carProfileService.save(inputDto);
    }


    @Operation(summary = "Retrieve a CarProfile by ID", description = "Fetches a single CarProfile using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CarProfile found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = CarProfileDTO.class))}),
            @ApiResponse(responseCode = "404", description = "CarProfile not found", content = @Content)
    })
    @GetMapping("/{vin}")
    public ResponseEntity<CarProfileDTO> findById(@PathVariable("vin") String vin) {
        Optional<CarProfileDTO> findOptional = carProfileService.findById(vin);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search CarProfile data", description = "Searches for CarProfile records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<CarProfileDTO> search(@RequestBody CarProfileSrchDTO searchDTO) {
        return carProfileService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing CarProfile", description = "Updates the details of an existing CarProfile by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CarProfile updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = CarProfileDTO.class))}),
            @ApiResponse(responseCode = "404", description = "CarProfile not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<CarProfileDTO> update(@RequestBody CarProfileDTO updateDto) {
        CarProfileDTO resultDto = carProfileService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple CarProfile entities", description = "Deletes a list of CarProfile entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each CarProfile entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more CarProfile entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<CarProfileKeyDTO> delDtoList) {
        List<Boolean> result = carProfileService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a CarProfile", description = "Deletes a CarProfile from the system using its unique identifier.")
    @DeleteMapping("/{vin}")
    public ResponseEntity<Boolean> delete(@PathVariable("vin") String vin) {
        if (!carProfileService.findById(vin).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = carProfileService.deleteById(vin);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for CarProfileDTO",
        description = "Fetches metadata for the CarProfileDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(CarProfileDTO.class));
    }
}
