//ecd:590105735H20250425111000_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.*;
import io.elasticore.blueprint.domain.parts.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing PartPosition entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/partPosition")
@RequiredArgsConstructor
@Tag(name = "PartPosition (partPosition)", description = "API for managing partPosition entities.")
public class PartPositionController {

    private final PartPositionService partPositionService;


    @Operation(summary = "Create a new PartPosition", description = "Registers a new PartPosition in the system.")
    @PostMapping
    public PartPositionDTO create(@Valid @RequestBody PartPositionDTO inputDto) {
        return partPositionService.save(inputDto);
    }


    @Operation(summary = "Retrieve a PartPosition by ID", description = "Fetches a single PartPosition using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "PartPosition found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = PartPositionDTO.class))}),
            @ApiResponse(responseCode = "404", description = "PartPosition not found", content = @Content)
    })
    @GetMapping("/{id}/{number}")
    public ResponseEntity<PartPositionDTO> findById(@PathVariable("id") String id ,@PathVariable("number") String number) {
        Optional<PartPositionDTO> findOptional = partPositionService.findById(id ,number);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search PartPosition data", description = "Searches for PartPosition records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<PartPositionDTO> search(@RequestBody PartPositionSrchDTO searchDTO) {
        return partPositionService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing PartPosition", description = "Updates the details of an existing PartPosition by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "PartPosition updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = PartPositionDTO.class))}),
            @ApiResponse(responseCode = "404", description = "PartPosition not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<PartPositionDTO> update(@RequestBody PartPositionDTO updateDto) {
        PartPositionDTO resultDto = partPositionService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple PartPosition entities", description = "Deletes a list of PartPosition entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each PartPosition entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more PartPosition entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<PartPositionKeyDTO> delDtoList) {
        List<Boolean> result = partPositionService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a PartPosition", description = "Deletes a PartPosition from the system using its unique identifier.")
    @DeleteMapping("/{id}/{number}")
    public ResponseEntity<Boolean> delete(@PathVariable("id") String id ,@PathVariable("number") String number) {
        if (!partPositionService.findById(id ,number).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = partPositionService.deleteById(id ,number);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for PartPositionDTO",
        description = "Fetches metadata for the PartPositionDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(PartPositionDTO.class));
    }
}
