//ecd:1501725548H20250425111000_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.*;
import io.elasticore.blueprint.domain.parts.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing PartGroupInfo entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/partGroupInfo")
@RequiredArgsConstructor
@Tag(name = "PartGroupInfo (partGroupInfo)", description = "API for managing partGroupInfo entities.")
public class PartGroupInfoController {

    private final PartGroupInfoService partGroupInfoService;


    @Operation(summary = "Create a new PartGroupInfo", description = "Registers a new PartGroupInfo in the system.")
    @PostMapping
    public PartGroupInfoDTO create(@Valid @RequestBody PartGroupInfoDTO inputDto) {
        return partGroupInfoService.save(inputDto);
    }


    @Operation(summary = "Retrieve a PartGroupInfo by ID", description = "Fetches a single PartGroupInfo using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "PartGroupInfo found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = PartGroupInfoDTO.class))}),
            @ApiResponse(responseCode = "404", description = "PartGroupInfo not found", content = @Content)
    })
    @GetMapping("/{carId}/{groupId}")
    public ResponseEntity<PartGroupInfoDTO> findById(@PathVariable("carId") String carId ,@PathVariable("groupId") String groupId) {
        Optional<PartGroupInfoDTO> findOptional = partGroupInfoService.findById(carId ,groupId);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search PartGroupInfo data", description = "Searches for PartGroupInfo records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<PartGroupInfoDTO> search(@RequestBody PartGroupInfoSrchDTO searchDTO) {
        return partGroupInfoService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing PartGroupInfo", description = "Updates the details of an existing PartGroupInfo by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "PartGroupInfo updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = PartGroupInfoDTO.class))}),
            @ApiResponse(responseCode = "404", description = "PartGroupInfo not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<PartGroupInfoDTO> update(@RequestBody PartGroupInfoDTO updateDto) {
        PartGroupInfoDTO resultDto = partGroupInfoService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple PartGroupInfo entities", description = "Deletes a list of PartGroupInfo entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each PartGroupInfo entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more PartGroupInfo entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<PartGroupInfoKeyDTO> delDtoList) {
        List<Boolean> result = partGroupInfoService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a PartGroupInfo", description = "Deletes a PartGroupInfo from the system using its unique identifier.")
    @DeleteMapping("/{carId}/{groupId}")
    public ResponseEntity<Boolean> delete(@PathVariable("carId") String carId ,@PathVariable("groupId") String groupId) {
        if (!partGroupInfoService.findById(carId ,groupId).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = partGroupInfoService.deleteById(carId ,groupId);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for PartGroupInfoDTO",
        description = "Fetches metadata for the PartGroupInfoDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(PartGroupInfoDTO.class));
    }
}
