//ecd:-48170251H20250409104819_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.MsgInput2;
import io.elasticore.blueprint.domain.parts.port.*;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.List;

/**
 * REST API controller for managing Article entities.
 * <p>
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 * <p>
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/test")
@RequiredArgsConstructor
@Tag(name = "Article (게시물)", description = "API for managing 게시물 entities.")
public class PartsTestController {

    private final PartsCatalogAdapter partsCatalogAdapter;

    private final EchoService echoService;


    @GetMapping("/case1")
    public ResponseEntity<?> case1() {

        String catalogId = "bmw";
        List carModels = partsCatalogAdapter.getCarModelList(catalogId);

        return ResponseEntity.ok(carModels);

    }

    @GetMapping("/case2")
    public ResponseEntity<?> case2() {

        String carId = "bmw";
        MsgInput2 build = MsgInput2.builder().id(1).build();

        HashMap hashMap = echoService.testEcho(build);

        return ResponseEntity.ok(hashMap);

    }
}
