//ecd:841204088H20250416200627_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.*;
import io.elasticore.blueprint.domain.parts.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing PartGroup entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/partGroup")
@RequiredArgsConstructor
@Tag(name = "PartGroup (차량 부품 그룹 정의)", description = "API for managing 차량 부품 그룹 정의 entities.")
public class PartGroupController {

    private final PartGroupService partGroupService;


    @Operation(summary = "Create a new PartGroup", description = "Registers a new PartGroup in the system.")
    @PostMapping
    public PartGroupDTO create(@Valid @RequestBody PartGroupDTO inputDto) {
        return partGroupService.save(inputDto);
    }


    @Operation(summary = "Retrieve a PartGroup by ID", description = "Fetches a single PartGroup using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "PartGroup found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = PartGroupDTO.class))}),
            @ApiResponse(responseCode = "404", description = "PartGroup not found", content = @Content)
    })
    @GetMapping("/{id}")
    public ResponseEntity<PartGroupDTO> findById(@PathVariable("id") String id) {
        Optional<PartGroupDTO> findOptional = partGroupService.findById(id);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search PartGroup data", description = "Searches for PartGroup records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<PartGroupDTO> search(@RequestBody PartGroupSrchDTO searchDTO) {
        return partGroupService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing PartGroup", description = "Updates the details of an existing PartGroup by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "PartGroup updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = PartGroupDTO.class))}),
            @ApiResponse(responseCode = "404", description = "PartGroup not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<PartGroupDTO> update(@RequestBody PartGroupDTO updateDto) {
        PartGroupDTO resultDto = partGroupService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple PartGroup entities", description = "Deletes a list of PartGroup entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each PartGroup entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more PartGroup entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<PartGroupKeyDTO> delDtoList) {
        List<Boolean> result = partGroupService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a PartGroup", description = "Deletes a PartGroup from the system using its unique identifier.")
    @DeleteMapping("/{id}")
    public ResponseEntity<Boolean> delete(@PathVariable("id") String id) {
        if (!partGroupService.findById(id).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = partGroupService.deleteById(id);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for PartGroupDTO",
        description = "Fetches metadata for the PartGroupDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(PartGroupDTO.class));
    }
}
