//ecd:-48170251H20250409104819_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.MsgInput2;
import io.elasticore.blueprint.domain.parts.port.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;

/**
 * REST API controller for managing Article entities.
 * <p>
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 * <p>
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/test")
@RequiredArgsConstructor
@Tag(name = "Article (게시물)", description = "API for managing 게시물 entities.")
public class PartsTestController {

    private final PartsCatalogAdapter partsCatalogAdapter;

    private final EchoService echoService;

    private final AligoHttpPortAdapter aligoHttpPortAdapter;


    private final String apiKey = "o4ocydls3wz5acrjney79s4j65a4f3xf";
    private final String userId = "mobillug";



    @GetMapping("/{catalogId}/parameters")
    @Operation(summary = "Get car parameters", description = "Retrieve parameters for a given catalog and modelId")
    public ResponseEntity<List> getCarParams(
            @PathVariable("catalogId") String catalogId,
            @RequestParam("modelId") String modelId,
            @RequestParam(name = "parameter", required = false) String[] parameter) {
        List carParams = partsCatalogAdapter.getCarParams(catalogId, modelId, parameter);

        return ResponseEntity.ok(carParams);
    }


    @GetMapping("/dummy2")
    public void testtest() {
        HashMap token = aligoHttpPortAdapter.createToken(apiKey, userId);
        System.err.println(token);
    }

    @GetMapping("/case1")
    public ResponseEntity<?> case1() {

        String catalogId = "bmw";
        List carModels = partsCatalogAdapter.getCarModelList(catalogId);

        return ResponseEntity.ok(carModels);

    }

    @GetMapping("/case2")
    public ResponseEntity<?> case2() {

        String carId = "bmw";
        MsgInput2 build = MsgInput2.builder().id(1).build();

        HashMap hashMap = echoService.testEcho(build);

        return ResponseEntity.ok(hashMap);

    }
}
