//ecd:-114050151H20250425111000_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.parts.controller;

import io.elasticore.blueprint.domain.parts.dto.*;
import io.elasticore.blueprint.domain.parts.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing SuggestGroup entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/parts/suggestGroup")
@RequiredArgsConstructor
@Tag(name = "SuggestGroup (suggestGroup)", description = "API for managing suggestGroup entities.")
public class SuggestGroupController {

    private final SuggestGroupService suggestGroupService;


    @Operation(summary = "Create a new SuggestGroup", description = "Registers a new SuggestGroup in the system.")
    @PostMapping
    public SuggestGroupDTO create(@Valid @RequestBody SuggestGroupDTO inputDto) {
        return suggestGroupService.save(inputDto);
    }


    @Operation(summary = "Retrieve a SuggestGroup by ID", description = "Fetches a single SuggestGroup using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "SuggestGroup found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = SuggestGroupDTO.class))}),
            @ApiResponse(responseCode = "404", description = "SuggestGroup not found", content = @Content)
    })
    @GetMapping("/{catalogId}/{sid}")
    public ResponseEntity<SuggestGroupDTO> findById(@PathVariable("catalogId") String catalogId ,@PathVariable("sid") String sid) {
        Optional<SuggestGroupDTO> findOptional = suggestGroupService.findById(catalogId ,sid);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search SuggestGroup data", description = "Searches for SuggestGroup records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<SuggestGroupDTO> search(@RequestBody SuggestGroupSrchDTO searchDTO) {
        return suggestGroupService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing SuggestGroup", description = "Updates the details of an existing SuggestGroup by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "SuggestGroup updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = SuggestGroupDTO.class))}),
            @ApiResponse(responseCode = "404", description = "SuggestGroup not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<SuggestGroupDTO> update(@RequestBody SuggestGroupDTO updateDto) {
        SuggestGroupDTO resultDto = suggestGroupService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple SuggestGroup entities", description = "Deletes a list of SuggestGroup entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each SuggestGroup entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more SuggestGroup entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<SuggestGroupKeyDTO> delDtoList) {
        List<Boolean> result = suggestGroupService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a SuggestGroup", description = "Deletes a SuggestGroup from the system using its unique identifier.")
    @DeleteMapping("/{catalogId}/{sid}")
    public ResponseEntity<Boolean> delete(@PathVariable("catalogId") String catalogId ,@PathVariable("sid") String sid) {
        if (!suggestGroupService.findById(catalogId ,sid).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = suggestGroupService.deleteById(catalogId ,sid);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for SuggestGroupDTO",
        description = "Fetches metadata for the SuggestGroupDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(SuggestGroupDTO.class));
    }
}
