//ecd:435612979H20250520141405_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package io.elasticore.blueprint.domain.bbs.controller;

import io.elasticore.blueprint.domain.bbs.dto.*;
import io.elasticore.blueprint.domain.bbs.service.*;

import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.elasticore.runtime.utils.DTOUtils;

/**
 * REST API controller for managing ArticlePart entities.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */
@RestController
@RequestMapping("/api/bbs/articlePart")
@RequiredArgsConstructor
@Tag(name = "ArticlePart (articlePart)", description = "API for managing articlePart entities.")
public class ArticlePartController {

    private final ArticlePartService articlePartService;


    @Operation(summary = "Create a new ArticlePart", description = "Registers a new ArticlePart in the system.")
    @PostMapping
    public ArticlePartDTO create(@Valid @RequestBody ArticlePartDTO inputDto) {
        return articlePartService.save(inputDto);
    }


    @Operation(summary = "Retrieve a ArticlePart by ID", description = "Fetches a single ArticlePart using its unique identifier.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "ArticlePart found successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ArticlePartDTO.class))}),
            @ApiResponse(responseCode = "404", description = "ArticlePart not found", content = @Content)
    })
    @GetMapping("/{article}/{partnerArticle}")
    public ResponseEntity<ArticlePartDTO> findById(@PathVariable("article") Article article ,@PathVariable("partnerArticle") Article partnerArticle) {
        Optional<ArticlePartDTO> findOptional = articlePartService.findById(article ,partnerArticle);
        return findOptional.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }


    @Operation(summary = "Search ArticlePart data", description = "Searches for ArticlePart records based on provided field criteria. All criteria are combined using logical AND.")
    @PostMapping("/search")
    public Page<ArticlePartDTO> search(@RequestBody ArticlePartSrchDTO searchDTO) {
        return articlePartService.findBySearch(searchDTO);
    }


    @Operation(summary = "Update an existing ArticlePart", description = "Updates the details of an existing ArticlePart by its ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "ArticlePart updated successfully", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ArticlePartDTO.class))}),
            @ApiResponse(responseCode = "404", description = "ArticlePart not found", content = @Content)
    })
    @PutMapping
    public ResponseEntity<ArticlePartDTO> update(@RequestBody ArticlePartDTO updateDto) {
        ArticlePartDTO resultDto = articlePartService.update(updateDto);
        return ResponseEntity.ok(resultDto);
    }

    @Operation(summary = "Delete multiple ArticlePart entities", description = "Deletes a list of ArticlePart entities based on their IDs provided in the request body.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Deletion result for each ArticlePart entity", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class, description = "List of booleans indicating success (true) or failure (false) for each entity"))}),
            @ApiResponse(responseCode = "404", description = "One or more ArticlePart entities not found", content = @Content)
    })
    @PostMapping("/delete")
    public ResponseEntity<List<Boolean>> delete(@RequestBody List<ArticlePartKeyDTO> delDtoList) {
        List<Boolean> result = articlePartService.delete(delDtoList);
        return ResponseEntity.ok(result);
    }


    @Operation(summary = "Delete a ArticlePart", description = "Deletes a ArticlePart from the system using its unique identifier.")
    @DeleteMapping("/{article}/{partnerArticle}")
    public ResponseEntity<Boolean> delete(@PathVariable("article") Article article ,@PathVariable("partnerArticle") Article partnerArticle) {
        if (!articlePartService.findById(article ,partnerArticle).isPresent()) {
            return ResponseEntity.notFound().build();
        }
        boolean result = articlePartService.deleteById(article ,partnerArticle);
        return ResponseEntity.ok(result);
    }

    @Operation(
        summary = "Retrieve metadata information for ArticlePartDTO",
        description = "Fetches metadata for the ArticlePartDTO, including field types, size limitations, and possible enumeration values, if applicable."
    )
    @GetMapping("/schema/info")
    public ResponseEntity<Map<String, Object>> getMetaInfo() {
        return ResponseEntity.ok(DTOUtils.getMetaInfo(ArticlePartDTO.class));
    }
}
