//ecd:7297675H20250402133543_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package com.xyrokorea.xyroplug.domain.channel.service;

import com.xyrokorea.xyroplug.domain.channel.repository.*;
import org.springframework.stereotype.Service;

@Service
public class ArticleService extends ArticleCoreService {

    public ArticleService(ChannelRepositoryHelper helper) {
        super(helper);
    }

}
