//ecd:1406565763H20250402001214_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package com.xyrokorea.xyroplug.domain.channel.service;

import com.xyrokorea.xyroplug.domain.channel.repository.*;
import org.springframework.stereotype.Service;

@Service
public class EnployeeService extends EnployeeCoreService {

    public EnployeeService(ChannelRepositoryHelper helper) {
        super(helper);
    }


    /// /

    ///

}
