//ecd:886237862H20250408175247_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package com.xyrokorea.xyroplug.domain.channel.service;

import com.xyrokorea.xyroplug.domain.channel.repository.*;
import org.springframework.stereotype.Service;

/**
 *
 * This class is intended for custom business logic that extends or overrides the default behavior
 * provided by MessageCoreService.
 *
 * Initially generated by ElastiCORE — a model-driven platform for
 * rapid Spring Boot service scaffolding.
 *
 * No longer managed by ElastiCORE. You may modify as needed,
 * but retain the marker for traceability.
 */

@Service
public class MessageService extends MessageCoreService {

    public MessageService(ChannelRepositoryHelper helper) {
        super(helper);
    }

}
