//ecd:-2046455750H20250403194437_V1.0
// Initially generated by ElastiCORE; no longer managed—do not remove this line.
package com.xyrokorea.xyroplug.domain.channel.service;

import com.xyrokorea.xyroplug.domain.channel.repository.*;
import org.springframework.stereotype.Service;

@Service
public class MessageService extends MessageCoreService {

    public MessageService(ChannelRepositoryHelper helper) {
        super(helper);
    }

}
